### ISSUE TITLE
F5 and standing up

### ISSUE THREAD

**Issue by IEmptyI** [PeaieceProductions/SpeedTweaks#1]
When I hit F5 in the middle of a battle it goes forward so its possible to win the game with doing absolutely nothing and when I stand up and hit D once or A twice I can't move after that and I have to restart

**Comment by PeaieceProductions** [comment]
The F5 Bug has been fixed ver. 0.1.1!
I don't have the issue with movement that you do, and I don't see how it could be associated by this mod, so it might help to double check the other mods you have installed, or validate the games files on steam :)

**Comment by PeaieceProductions** [comment]
Thanks for reporting the issue!

**Comment by IEmptyI** [comment]
> The F5 Bug has been fixed ver. 0.1.1! I don't have the issue with movement that you do, and I don't see how it could be associated by this mod, so it might help to double check the other mods you have installed, or validate the games files on steam :)

Alright ill see what other mods could be causing the issue. Also thank you for fixing the F5 bug!
