### ISSUE TITLE
Bug: F5 does the same thing as F9

### ISSUE THREAD

**Issue by Rayzefi** [PeaieceProductions/SpeedTweaks#1]
0.9.1 and 0.9.0

**Comment by PeaieceProductions** [comment]
Thanks for the report,
are you using the mod with Part 1 or Kaycees Mod?
If it's Kaycees mod, do you have a saved game to continue?
If not then both buttons will load you to the new game screen

**Comment by Rayzefi** [comment]
Sorry for late reply. I was using the mod with Part 1 (The GOG version not the Steam version, so I can't get Kaycee's Mod)
The F5 works as intended in version 0.1.4 but not 0.9.0/1/2

**Comment by Rayzefi** [comment]
Sorry for late reply
I was using the mod with Part 1 (The GOG version not the Steam version, so I can't get Kaycee's Mod)
The F5 works as intended in version 0.1.4 but not 0.9.0/1/2

**Comment by PeaieceProductions** [comment]
This issue has been fixed in 0.9.3!
Thanks for the report and sorry for the inconvenience.

**Comment by Rayzefi** [comment]
Thanks for the fix and the mod, it's been very helpful!
