### ISSUE TITLE
F5 not restarting run just last battle or board space (Self Explanatory)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PeaieceProductions/SpeedTweaks#2]

**Comment by P3rf3ctXZer0** [comment]
Idea - Maybe Force the scene right after the camera flash death scene? You could use unity flags to force load that part. (I am not a unity coder so I am not familiar with how to make it work but it would definitely be foolproof if you could set it up that way.

**Comment by P3rf3ctXZer0** [comment]
Hey so I was doing some digging and a quick hook is have your mod load scene 

![yG5Aw2N 1](https://user-images.githubusercontent.com/10351221/145904712-f7ed7875-4c47-4d91-b98e-2a1efc1388ed.png)

**Comment by PeaieceProductions** [comment]
Hey, you can use F9 to restart the run :), F5 is just to reset it

**Comment by PeaieceProductions** [comment]
I've made the documentation clearer to avoid confusion, thanks for your help!

**Comment by P3rf3ctXZer0** [comment]
lol thank you XD
